### ISSUE TITLE
Doubling up on Weapons?

### ISSUE THREAD

**Issue by giancola** [Sproute777/td#1]
Thanks for making the fixes so quickly.

I think I found another issue, able to double-up on towers. Can't quite nail down what was different that allowed it.

<img width="166" alt="TD BUG 2022-02-04 083106" src="https://user-images.githubusercontent.com/217292/152566671-eab59cb3-2378-4996-b4c3-2e4e410d81c6.png">

Would it be ok if I created a PullRequest for this to the main repo? It would be better if we all work on a single version rather than fracture.

Can I have your email address?

Thanks
Tony

**Comment by s1r1m1r1** [comment]
I can
